template: testify

packages:
  # spyder/internal/cli:
  #   interfaces:
  #     CommandHandler:
  #   config:
  #     dir: "{{.InterfaceDir}}/mocks"
  #     filename: "cli_mock.go"
  #     pkgname: "cli_test"
  #     formatter: gofmt

  spyder/internal/database/storage:
    interfaces:
      CommandStorage:
      QueryStorage:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "storage_mock.go"
      pkgname: "storage_test"
      formatter: gofmt

  spyder/internal/database:
    interfaces:
      ComputeLayer:
      StorageLayer:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      filename: "database_mock.go"
      pkgname: "database_test"
      formatter: gofmt
