// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cli_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandHandler creates a new instance of MockCommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandHandler {
	mock := &MockCommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandHandler is an autogenerated mock type for the CommandHandler type
type MockCommandHandler struct {
	mock.Mock
}

type MockCommandHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandHandler) EXPECT() *MockCommandHandler_Expecter {
	return &MockCommandHandler_Expecter{mock: &_m.Mock}
}

// ComputeHandler provides a mock function for the type MockCommandHandler
func (_mock *MockCommandHandler) ComputeHandler(ctx context.Context, raw string) (string, error) {
	ret := _mock.Called(ctx, raw)

	if len(ret) == 0 {
		panic("no return value specified for ComputeHandler")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, raw)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, raw)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandHandler_ComputeHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputeHandler'
type MockCommandHandler_ComputeHandler_Call struct {
	*mock.Call
}

// ComputeHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - raw string
func (_e *MockCommandHandler_Expecter) ComputeHandler(ctx interface{}, raw interface{}) *MockCommandHandler_ComputeHandler_Call {
	return &MockCommandHandler_ComputeHandler_Call{Call: _e.mock.On("ComputeHandler", ctx, raw)}
}

func (_c *MockCommandHandler_ComputeHandler_Call) Run(run func(ctx context.Context, raw string)) *MockCommandHandler_ComputeHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommandHandler_ComputeHandler_Call) Return(s string, err error) *MockCommandHandler_ComputeHandler_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCommandHandler_ComputeHandler_Call) RunAndReturn(run func(ctx context.Context, raw string) (string, error)) *MockCommandHandler_ComputeHandler_Call {
	_c.Call.Return(run)
	return _c
}
