// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package compute_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandCompute creates a new instance of MockCommandCompute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandCompute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandCompute {
	mock := &MockCommandCompute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandCompute is an autogenerated mock type for the CommandCompute type
type MockCommandCompute struct {
	mock.Mock
}

type MockCommandCompute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandCompute) EXPECT() *MockCommandCompute_Expecter {
	return &MockCommandCompute_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type MockCommandCompute
func (_mock *MockCommandCompute) Del(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandCompute_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockCommandCompute_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCommandCompute_Expecter) Del(ctx interface{}, key interface{}) *MockCommandCompute_Del_Call {
	return &MockCommandCompute_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *MockCommandCompute_Del_Call) Run(run func(ctx context.Context, key string)) *MockCommandCompute_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommandCompute_Del_Call) Return(err error) *MockCommandCompute_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandCompute_Del_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockCommandCompute_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCommandCompute
func (_mock *MockCommandCompute) Set(ctx context.Context, key string, value string) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandCompute_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCommandCompute_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *MockCommandCompute_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockCommandCompute_Set_Call {
	return &MockCommandCompute_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockCommandCompute_Set_Call) Run(run func(ctx context.Context, key string, value string)) *MockCommandCompute_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommandCompute_Set_Call) Return(err error) *MockCommandCompute_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandCompute_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string) error) *MockCommandCompute_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryCompute creates a new instance of MockQueryCompute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryCompute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryCompute {
	mock := &MockQueryCompute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryCompute is an autogenerated mock type for the QueryCompute type
type MockQueryCompute struct {
	mock.Mock
}

type MockQueryCompute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryCompute) EXPECT() *MockQueryCompute_Expecter {
	return &MockQueryCompute_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockQueryCompute
func (_mock *MockQueryCompute) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryCompute_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockQueryCompute_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockQueryCompute_Expecter) Get(ctx interface{}, key interface{}) *MockQueryCompute_Get_Call {
	return &MockQueryCompute_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockQueryCompute_Get_Call) Run(run func(ctx context.Context, key string)) *MockQueryCompute_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryCompute_Get_Call) Return(s string, err error) *MockQueryCompute_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockQueryCompute_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockQueryCompute_Get_Call {
	_c.Call.Return(run)
	return _c
}
